import type { UserProgress } from '../contexts/AuthContext';

export interface PerformanceReport {
  overallAccuracy: number;
  totalQuestions: number;
  weakSpecialties: Array<{
    name: string;
    accuracy: number;
    questionsAnswered: number;
    recommendations: string[];
  }>;
  strongSpecialties: Array<{
    name: string;
    accuracy: number;
    questionsAnswered: number;
  }>;
  recentTrends: {
    improvementAreas: string[];
    concernAreas: string[];
  };
  recommendedActions: string[];
  nextSteps: string[];
}

export interface AutoGeneratedMaterial {
  id: string;
  title: string;
  specialty: string;
  type: 'resumo' | 'exercicio' | 'video' | 'flashcard';
  priority: 'urgent' | 'high' | 'medium' | 'low';
  reason: string;
  content: {
    topics: string[];
    estimatedTime: string;
    difficulty: 'easy' | 'medium' | 'hard';
  };
  triggerReason: string; // Por que foi gerado automaticamente
}

/**
 * Gera relatório de performance automaticamente
 */
export function generatePerformanceReport(progress: UserProgress): PerformanceReport {
  const specialtyStats = Object.entries(progress.specialties).map(([name, stats]) => ({
    name,
    accuracy: stats.total > 0 ? (stats.correct / stats.total) * 100 : 0,
    total: stats.total,
    correct: stats.correct,
  }));

  // Especialidades fracas (< 70% de acerto e pelo menos 5 questões)
  const weakSpecialties = specialtyStats
    .filter(s => s.total >= 5 && s.accuracy < 70)
    .sort((a, b) => a.accuracy - b.accuracy)
    .map(s => ({
      name: s.name,
      accuracy: s.accuracy,
      questionsAnswered: s.total,
      recommendations: generateRecommendations(s.accuracy, s.total),
    }));

  // Especialidades fortes (≥ 80% de acerto)
  const strongSpecialties = specialtyStats
    .filter(s => s.total >= 5 && s.accuracy >= 80)
    .sort((a, b) => b.accuracy - a.accuracy)
    .map(s => ({
      name: s.name,
      accuracy: s.accuracy,
      questionsAnswered: s.total,
    }));

  // Análise de tendências recentes (últimas 10 questões)
  const recentQuestions = progress.questionHistory.slice(-10);
  const recentAccuracy = recentQuestions.length > 0
    ? (recentQuestions.filter(q => q.correct).length / recentQuestions.length) * 100
    : 0;

  const overallAccuracy = progress.totalQuestions > 0
    ? (progress.correctAnswers / progress.totalQuestions) * 100
    : 0;

  const improvementAreas: string[] = [];
  const concernAreas: string[] = [];

  // Detectar áreas de melhoria ou preocupação
  if (recentAccuracy > overallAccuracy + 10) {
    improvementAreas.push('Desempenho recente melhorando significativamente');
  } else if (recentAccuracy < overallAccuracy - 10) {
    concernAreas.push('Desempenho recente em queda - considere revisar conceitos básicos');
  }

  weakSpecialties.forEach(ws => {
    if (ws.accuracy < 50) {
      concernAreas.push(`${ws.name}: Desempenho crítico (${ws.accuracy.toFixed(0)}%)`);
    } else if (ws.accuracy < 70) {
      concernAreas.push(`${ws.name}: Requer atenção (${ws.accuracy.toFixed(0)}%)`);
    }
  });

  // Ações recomendadas
  const recommendedActions = generateRecommendedActions(
    weakSpecialties,
    progress
  );

  // Próximos passos
  const nextSteps = generateNextSteps(weakSpecialties);

  return {
    overallAccuracy,
    totalQuestions: progress.totalQuestions,
    weakSpecialties,
    strongSpecialties,
    recentTrends: {
      improvementAreas,
      concernAreas,
    },
    recommendedActions,
    nextSteps,
  };
}

/**
 * Gera recomendações específicas para uma especialidade
 */
function generateRecommendations(
  accuracy: number,
  total: number
): string[] {
  const recommendations: string[] = [];

  if (accuracy < 50) {
    recommendations.push('🚨 URGENTE: Revisar conceitos fundamentais');
    recommendations.push('📚 Estudar material básico antes de tentar questões');
    recommendations.push('👨‍🏫 Considerar ajuda de um mentor ou professor');
  } else if (accuracy < 60) {
    recommendations.push('⚠️ Reforçar conceitos básicos');
    recommendations.push('📖 Fazer resumos dos principais tópicos');
    recommendations.push('💡 Resolver questões comentadas');
  } else if (accuracy < 70) {
    recommendations.push('📊 Identificar pontos específicos de dificuldade');
    recommendations.push('🎯 Praticar com questões de nível médio');
    recommendations.push('🔄 Revisar erros anteriores');
  }

  if (total < 10) {
    recommendations.push('📈 Responder mais questões para melhor análise');
  }

  return recommendations;
}

/**
 * Gera ações recomendadas gerais
 */
function generateRecommendedActions(
  weakSpecialties: PerformanceReport['weakSpecialties'],
  progress: UserProgress
): string[] {
  const actions: string[] = [];

  // Baseado em especialidades fracas
  if (weakSpecialties.length > 0) {
    actions.push(`Focar nos próximos 7 dias em: ${weakSpecialties.slice(0, 3).map(w => w.name).join(', ')}`);
    actions.push('Dedicar pelo menos 1 hora diária às especialidades com dificuldade');
  }

  // Baseado em metas
  const dailyGoal = progress.goals?.dailyQuestions || 10;
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const todayQuestions = progress.questionHistory?.filter(q => {
    const qDate = new Date(q.timestamp);
    qDate.setHours(0, 0, 0, 0);
    return qDate.getTime() === today.getTime();
  }).length || 0;

  if (todayQuestions < dailyGoal) {
    actions.push(`Completar meta diária: faltam ${dailyGoal - todayQuestions} questões hoje`);
  }

  // Baseado em streak
  if (progress.streakDays < 7) {
    actions.push('Manter consistência: estudar todos os dias para criar o hábito');
  } else {
    actions.push(`Manter streak atual de ${progress.streakDays} dias! Continue assim!`);
  }

  // Diversificação
  const specialtiesStudied = Object.keys(progress.specialties).length;
  if (specialtiesStudied < 5) {
    actions.push('Diversificar estudos: explorar novas especialidades');
  }

  return actions;
}

/**
 * Gera próximos passos personalizados
 */
function generateNextSteps(
  weakSpecialties: PerformanceReport['weakSpecialties']
): string[] {
  const steps: string[] = [];

  if (weakSpecialties.length > 0) {
    const weakest = weakSpecialties[0];
    steps.push(`1. Estudar material básico de ${weakest.name}`);
    steps.push(`2. Resolver 10 questões fáceis de ${weakest.name}`);
    steps.push(`3. Revisar erros e fazer anotações`);
    
    if (weakSpecialties.length > 1) {
      const secondWeakest = weakSpecialties[1];
      steps.push(`4. Iniciar revisão de ${secondWeakest.name}`);
    }
  } else {
    steps.push('1. Explorar novas especialidades');
    steps.push('2. Aumentar nível de dificuldade das questões');
    steps.push('3. Resolver casos clínicos complexos');
  }

  steps.push('5. Revisar material de estudo gerado automaticamente');
  steps.push('6. Manter rotina diária de estudos');

  return steps;
}

/**
 * Gera materiais automaticamente baseado em dificuldades detectadas
 */
export function autoGenerateMaterials(progress: UserProgress): AutoGeneratedMaterial[] {
  const materials: AutoGeneratedMaterial[] = [];
  const report = generatePerformanceReport(progress);

  // Para cada especialidade fraca, gerar materiais
  report.weakSpecialties.forEach((weak, index) => {
    const urgency = weak.accuracy < 50 ? 'urgent' : weak.accuracy < 60 ? 'high' : 'medium';

    // Material 1: Resumo básico
    materials.push({
      id: `auto-resumo-${weak.name}-${Date.now()}-${index}`,
      title: `Revisão Essencial: ${weak.name}`,
      specialty: weak.name,
      type: 'resumo',
      priority: urgency,
      reason: `Desempenho em ${weak.name}: ${weak.accuracy.toFixed(0)}% de acerto`,
      content: {
        topics: [
          'Conceitos fundamentais',
          'Fisiopatologia básica',
          'Quadro clínico típico',
          'Diagnóstico diferencial',
          'Abordagem terapêutica inicial',
        ],
        estimatedTime: '45 min',
        difficulty: 'easy',
      },
      triggerReason: `Gerado automaticamente devido ao desempenho abaixo de 70% (${weak.accuracy.toFixed(0)}%)`,
    });

    // Material 2: Exercícios dirigidos
    materials.push({
      id: `auto-exercicio-${weak.name}-${Date.now()}-${index}`,
      title: `Exercícios Práticos: ${weak.name}`,
      specialty: weak.name,
      type: 'exercicio',
      priority: urgency === 'urgent' ? 'high' : 'medium',
      reason: 'Prática necessária para fixação',
      content: {
        topics: [
          '20 questões progressivas',
          'Explicação detalhada de cada resposta',
          'Dicas e macetes',
        ],
        estimatedTime: '60 min',
        difficulty: weak.accuracy < 50 ? 'easy' : 'medium',
      },
      triggerReason: `Criado para reforçar conhecimentos em ${weak.name}`,
    });

    // Material 3: Flashcards (se muito crítico)
    if (weak.accuracy < 60) {
      materials.push({
        id: `auto-flashcard-${weak.name}-${Date.now()}-${index}`,
        title: `Flashcards: Conceitos-chave de ${weak.name}`,
        specialty: weak.name,
        type: 'flashcard',
        priority: 'high',
        reason: 'Memorização ativa de conceitos essenciais',
        content: {
          topics: [
            '50 flashcards com conceitos fundamentais',
            'Perguntas e respostas diretas',
            'Revisão espaçada',
          ],
          estimatedTime: '20 min/dia',
          difficulty: 'easy',
        },
        triggerReason: `Performance crítica detectada: ${weak.accuracy.toFixed(0)}%`,
      });
    }
  });

  // Materiais para áreas de melhoria recente
  if (report.recentTrends.concernAreas.length > 0) {
    materials.push({
      id: `auto-alerta-${Date.now()}`,
      title: 'Revisão Geral: Reforço de Conceitos',
      specialty: 'Multidisciplinar',
      type: 'resumo',
      priority: 'high',
      reason: 'Queda de desempenho recente detectada',
      content: {
        topics: [
          'Revisão dos erros mais frequentes',
          'Conceitos que costumam confundir',
          'Estratégias de prova',
        ],
        estimatedTime: '30 min',
        difficulty: 'medium',
      },
      triggerReason: 'Sistema detectou queda no desempenho recente',
    });
  }

  // Se o aluno está indo bem, sugerir desafios
  if (report.strongSpecialties.length >= 3 && report.weakSpecialties.length === 0) {
    const topSpecialty = report.strongSpecialties[0];
    materials.push({
      id: `auto-desafio-${Date.now()}`,
      title: `Casos Complexos: ${topSpecialty.name}`,
      specialty: topSpecialty.name,
      type: 'video',
      priority: 'medium',
      reason: `Excelente desempenho em ${topSpecialty.name} (${topSpecialty.accuracy.toFixed(0)}%)`,
      content: {
        topics: [
          'Casos clínicos avançados',
          'Discussão de diagnósticos diferenciais',
          'Tomada de decisão complexa',
        ],
        estimatedTime: '40 min',
        difficulty: 'hard',
      },
      triggerReason: `Criado para desafiar: performance acima de 80%`,
    });
  }

  return materials.sort((a, b) => {
    const priorityOrder = { urgent: 0, high: 1, medium: 2, low: 3 };
    return priorityOrder[a.priority] - priorityOrder[b.priority];
  });
}

/**
 * Verifica se deve gerar novos materiais automaticamente
 */
export function shouldGenerateNewMaterials(progress: UserProgress): boolean {
  // Gerar a cada 10 questões
  return progress.totalQuestions > 0 && progress.totalQuestions % 10 === 0;
}

/**
 * Formata o relatório para exibição
 */
export function formatReportForDisplay(report: PerformanceReport): string {
  let text = '# 📊 Relatório de Performance\n\n';
  
  text += `**Aproveitamento Geral:** ${report.overallAccuracy.toFixed(1)}%\n`;
  text += `**Total de Questões:** ${report.totalQuestions}\n\n`;
  
  if (report.weakSpecialties.length > 0) {
    text += '## ⚠️ Especialidades que Precisam de Atenção\n\n';
    report.weakSpecialties.forEach(ws => {
      text += `### ${ws.name} - ${ws.accuracy.toFixed(0)}%\n`;
      text += `Questões: ${ws.questionsAnswered}\n`;
      text += 'Recomendações:\n';
      ws.recommendations.forEach(rec => {
        text += `- ${rec}\n`;
      });
      text += '\n';
    });
  }
  
  if (report.strongSpecialties.length > 0) {
    text += '## ✅ Especialidades com Bom Desempenho\n\n';
    report.strongSpecialties.forEach(ss => {
      text += `- **${ss.name}**: ${ss.accuracy.toFixed(0)}% (${ss.questionsAnswered} questões)\n`;
    });
    text += '\n';
  }
  
  if (report.recentTrends.concernAreas.length > 0) {
    text += '## 🔍 Pontos de Atenção\n\n';
    report.recentTrends.concernAreas.forEach(area => {
      text += `- ${area}\n`;
    });
    text += '\n';
  }
  
  if (report.recommendedActions.length > 0) {
    text += '## 🎯 Ações Recomendadas\n\n';
    report.recommendedActions.forEach((action, i) => {
      text += `${i + 1}. ${action}\n`;
    });
    text += '\n';
  }
  
  if (report.nextSteps.length > 0) {
    text += '## 📋 Próximos Passos\n\n';
    report.nextSteps.forEach(step => {
      text += `${step}\n`;
    });
  }
  
  return text;
}
