import React, { useState, useEffect } from 'react';
import DashboardLayout from '../components/DashboardLayout';
import { BookOpen, FileText, Video, TrendingUp, Star, Clock, Target, Sparkles, BookMarked, Brain, Award, AlertCircle } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { autoGenerateMaterials, type AutoGeneratedMaterial } from '../services/reports';

interface StudyMaterial {
  id: string;
  title: string;
  specialty: string;
  type: 'resumo' | 'artigo' | 'video';
  difficulty: 'easy' | 'medium' | 'hard';
  duration: string;
  topics: string[];
  priority: 'high' | 'medium' | 'low';
  reason: string;
}

const EstudosPage: React.FC = () => {
  const { progress } = useAuth();
  const [materials, setMaterials] = useState<StudyMaterial[]>([]);
  const [activeFilter, setActiveFilter] = useState<'all' | 'resumo' | 'artigo' | 'video'>('all');
  const [loading, setLoading] = useState(false);

  // Gerar materiais personalizados baseados no progresso
  useEffect(() => {
    generatePersonalizedMaterials();
  }, [progress]);

  const generatePersonalizedMaterials = () => {
    // Primeiro, gerar materiais automáticos baseados em dificuldades
    const autoMaterials = autoGenerateMaterials(progress);
    
    const generatedMaterials: StudyMaterial[] = [];
    
    // Converter materiais automáticos para o formato StudyMaterial
    autoMaterials.forEach((autoMat) => {
      const priorityMap: Record<string, 'high' | 'medium' | 'low'> = {
        urgent: 'high',
        high: 'high',
        medium: 'medium',
        low: 'low',
      };
      
      generatedMaterials.push({
        id: autoMat.id,
        title: autoMat.title,
        specialty: autoMat.specialty,
        type: autoMat.type === 'exercicio' ? 'resumo' : autoMat.type === 'flashcard' ? 'resumo' : autoMat.type,
        difficulty: autoMat.content.difficulty,
        duration: autoMat.content.estimatedTime,
        topics: autoMat.content.topics,
        priority: priorityMap[autoMat.priority],
        reason: `${autoMat.reason} - ${autoMat.triggerReason}`,
      });
    });

    // Análise de especialidades
    const specialtyStats = Object.entries(progress.specialties).map(([name, stats]) => ({
      name,
      accuracy: stats.correct > 0 ? (stats.correct / stats.total) * 100 : 0,
      total: stats.total,
    }));

    // Especialidades que precisam de reforço (< 70% de acerto)
    const weakSpecialties = specialtyStats
      .filter(s => s.total > 0 && s.accuracy < 70)
      .sort((a, b) => a.accuracy - b.accuracy)
      .slice(0, 3);

    weakSpecialties.forEach((spec, index) => {
      // Resumo para reforço
      generatedMaterials.push({
        id: `resumo-${spec.name}-${index}`,
        title: `Revisão Essencial: ${spec.name}`,
        specialty: spec.name,
        type: 'resumo',
        difficulty: 'medium',
        duration: '30-45 min',
        topics: ['Conceitos fundamentais', 'Diagnóstico diferencial', 'Tratamento'],
        priority: 'high',
        reason: `Você acertou apenas ${spec.accuracy.toFixed(0)}% das questões. Reforce os conceitos básicos!`,
      });

      // Artigo científico
      generatedMaterials.push({
        id: `artigo-${spec.name}-${index}`,
        title: `Atualizações em ${spec.name}`,
        specialty: spec.name,
        type: 'artigo',
        difficulty: 'hard',
        duration: '20-30 min',
        topics: ['Evidências recentes', 'Guidelines atualizados'],
        priority: 'high',
        reason: 'Aprofunde seu conhecimento com evidências científicas recentes',
      });
    });

    // Especialidades favoritas (bem performadas)
    const strongSpecialties = specialtyStats
      .filter(s => s.total > 0 && s.accuracy >= 70)
      .sort((a, b) => b.accuracy - a.accuracy)
      .slice(0, 2);

    strongSpecialties.forEach((spec, index) => {
      generatedMaterials.push({
        id: `video-${spec.name}-${index}`,
        title: `Casos Clínicos Avançados: ${spec.name}`,
        specialty: spec.name,
        type: 'video',
        difficulty: 'hard',
        duration: '15-25 min',
        topics: ['Casos complexos', 'Tomada de decisão'],
        priority: 'medium',
        reason: `Excelente performance (${spec.accuracy.toFixed(0)}%)! Continue avançando com casos práticos`,
      });
    });

    // Preferências do usuário
    progress.preferences.favoriteSpecialties.forEach((fav, index) => {
      if (!generatedMaterials.find(m => m.specialty === fav)) {
        generatedMaterials.push({
          id: `pref-${fav}-${index}`,
          title: `Guia Completo: ${fav}`,
          specialty: fav,
          type: index % 2 === 0 ? 'resumo' : 'video',
          difficulty: progress.preferences.preferredDifficulty,
          duration: '25-40 min',
          topics: ['Revisão completa', 'Questões frequentes'],
          priority: 'medium',
          reason: 'Baseado nas suas especialidades favoritas',
        });
      }
    });

    // Tópicos sugeridos pela IA
    progress.suggestedTopics.slice(0, 3).forEach((topic, index) => {
      generatedMaterials.push({
        id: `ai-${topic.topic}-${index}`,
        title: topic.topic,
        specialty: topic.specialty,
        type: 'resumo',
        difficulty: 'medium',
        duration: '30 min',
        topics: [topic.reason],
        priority: topic.priority,
        reason: topic.reason,
      });
    });

    // Conteúdo geral para iniciantes
    if (progress.totalQuestions < 10) {
      generatedMaterials.push(
        {
          id: 'intro-1',
          title: 'Introdução à Medicina de Emergência',
          specialty: 'Clínica Médica',
          type: 'video',
          difficulty: 'easy',
          duration: '20 min',
          topics: ['Triagem', 'Prioridades', 'Protocolos básicos'],
          priority: 'high',
          reason: 'Fundamentos essenciais para começar seus estudos',
        },
        {
          id: 'intro-2',
          title: 'Anatomia Aplicada',
          specialty: 'Cirurgia Geral',
          type: 'resumo',
          difficulty: 'easy',
          duration: '35 min',
          topics: ['Anatomia regional', 'Relações anatômicas importantes'],
          priority: 'high',
          reason: 'Base fundamental para todas as especialidades',
        }
      );
    }

    setMaterials(generatedMaterials);
  };

  const filteredMaterials = activeFilter === 'all' 
    ? materials 
    : materials.filter(m => m.type === activeFilter);

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high': return 'text-red-600 bg-red-50 border-red-200';
      case 'medium': return 'text-orange-600 bg-orange-50 border-orange-200';
      case 'low': return 'text-blue-600 bg-blue-50 border-blue-200';
      default: return 'text-gray-600 bg-gray-50 border-gray-200';
    }
  };

  const getDifficultyLabel = (difficulty: string) => {
    switch (difficulty) {
      case 'easy': return '⭐ Básico';
      case 'medium': return '⭐⭐ Intermediário';
      case 'hard': return '⭐⭐⭐ Avançado';
      default: return difficulty;
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'resumo': return <BookOpen className="w-5 h-5" />;
      case 'artigo': return <FileText className="w-5 h-5" />;
      case 'video': return <Video className="w-5 h-5" />;
      default: return <BookOpen className="w-5 h-5" />;
    }
  };

  const stats = {
    totalMaterials: materials.length,
    highPriority: materials.filter(m => m.priority === 'high').length,
    completedToday: 0, // Pode ser implementado depois
  };

  return (
    <DashboardLayout>
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-4xl font-bold text-gray-900 mb-2">Material de Estudo</h1>
            <p className="text-gray-600">Conteúdo personalizado baseado no seu progresso</p>
          </div>
          <div className="flex items-center space-x-2 text-sm">
            <Sparkles className="w-5 h-5 text-purple-500" />
            <span className="text-gray-600">Atualizado em tempo real</span>
          </div>
        </div>

        {/* Cards de Estatísticas */}
        <div className="grid md:grid-cols-3 gap-6 mb-8">
          <div className="bg-gradient-to-br from-blue-500 to-blue-600 rounded-2xl shadow-lg p-6 text-white">
            <BookMarked className="w-10 h-10 mb-3 opacity-80" />
            <div className="text-3xl font-bold mb-1">{stats.totalMaterials}</div>
            <div className="text-blue-100">Materiais Disponíveis</div>
          </div>

          <div className="bg-gradient-to-br from-red-500 to-red-600 rounded-2xl shadow-lg p-6 text-white">
            <Target className="w-10 h-10 mb-3 opacity-80" />
            <div className="text-3xl font-bold mb-1">{stats.highPriority}</div>
            <div className="text-red-100">Alta Prioridade</div>
          </div>

          <div className="bg-gradient-to-br from-green-500 to-green-600 rounded-2xl shadow-lg p-6 text-white">
            <Brain className="w-10 h-10 mb-3 opacity-80" />
            <div className="text-3xl font-bold mb-1">{progress.totalQuestions}</div>
            <div className="text-green-100">Questões Respondidas</div>
          </div>
        </div>

        {/* Filtros */}
        <div className="bg-white rounded-2xl shadow-lg p-4 mb-6">
          <div className="flex items-center space-x-2 overflow-x-auto">
            <button
              onClick={() => setActiveFilter('all')}
              className={`px-4 py-2 rounded-lg font-medium transition-all whitespace-nowrap ${
                activeFilter === 'all'
                  ? 'bg-blue-500 text-white'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
            >
              Todos ({materials.length})
            </button>
            <button
              onClick={() => setActiveFilter('resumo')}
              className={`px-4 py-2 rounded-lg font-medium transition-all whitespace-nowrap flex items-center space-x-2 ${
                activeFilter === 'resumo'
                  ? 'bg-blue-500 text-white'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
            >
              <BookOpen className="w-4 h-4" />
              <span>Resumos ({materials.filter(m => m.type === 'resumo').length})</span>
            </button>
            <button
              onClick={() => setActiveFilter('artigo')}
              className={`px-4 py-2 rounded-lg font-medium transition-all whitespace-nowrap flex items-center space-x-2 ${
                activeFilter === 'artigo'
                  ? 'bg-blue-500 text-white'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
            >
              <FileText className="w-4 h-4" />
              <span>Artigos ({materials.filter(m => m.type === 'artigo').length})</span>
            </button>
            <button
              onClick={() => setActiveFilter('video')}
              className={`px-4 py-2 rounded-lg font-medium transition-all whitespace-nowrap flex items-center space-x-2 ${
                activeFilter === 'video'
                  ? 'bg-blue-500 text-white'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
            >
              <Video className="w-4 h-4" />
              <span>Vídeos ({materials.filter(m => m.type === 'video').length})</span>
            </button>
          </div>
        </div>

        {/* Lista de Materiais */}
        {filteredMaterials.length === 0 ? (
          <div className="bg-white rounded-2xl shadow-lg p-12 text-center">
            <BookOpen className="w-16 h-16 text-gray-300 mx-auto mb-4" />
            <h3 className="text-xl font-bold text-gray-900 mb-2">Comece a estudar!</h3>
            <p className="text-gray-600">
              Responda algumas questões para receber recomendações personalizadas de estudo
            </p>
          </div>
        ) : (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredMaterials.map((material) => (
              <div
                key={material.id}
                className="bg-white rounded-2xl shadow-lg hover:shadow-xl transition-all p-6 cursor-pointer group relative overflow-hidden"
              >
                {/* Badge de Auto-Gerado */}
                {material.id.startsWith('auto-') && (
                  <div className="absolute top-0 right-0">
                    <div className="bg-gradient-to-br from-purple-500 to-pink-500 text-white text-xs font-bold px-3 py-1 rounded-bl-lg flex items-center space-x-1">
                      <Sparkles className="w-3 h-3" />
                      <span>Auto-Gerado</span>
                    </div>
                  </div>
                )}
                
                {/* Header */}
                <div className="flex items-start justify-between mb-4">
                  <div className="flex items-center space-x-3">
                    <div className={`p-2 rounded-lg ${
                      material.type === 'resumo' ? 'bg-blue-100 text-blue-600' :
                      material.type === 'artigo' ? 'bg-green-100 text-green-600' :
                      'bg-purple-100 text-purple-600'
                    }`}>
                      {getTypeIcon(material.type)}
                    </div>
                    <div>
                      <div className={`text-xs font-semibold px-2 py-1 rounded border ${getPriorityColor(material.priority)}`}>
                        {material.priority === 'high' ? '🔥 Prioritário' : 
                         material.priority === 'medium' ? '⚡ Recomendado' : 
                         '📌 Sugerido'}
                      </div>
                    </div>
                  </div>
                </div>

                {/* Título e Especialidade */}
                <h3 className="text-lg font-bold text-gray-900 mb-2 group-hover:text-blue-600 transition-colors">
                  {material.title}
                </h3>
                <div className="text-sm text-gray-500 mb-3 flex items-center space-x-2">
                  <span className="px-2 py-1 bg-gray-100 rounded">{material.specialty}</span>
                  <span>•</span>
                  <Clock className="w-4 h-4" />
                  <span>{material.duration}</span>
                </div>

                {/* Motivo */}
                <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mb-4">
                  <p className="text-sm text-blue-900">
                    <strong>Por quê?</strong> {material.reason}
                  </p>
                </div>

                {/* Dificuldade */}
                <div className="text-sm text-gray-600 mb-4">
                  {getDifficultyLabel(material.difficulty)}
                </div>

                {/* Tópicos */}
                <div className="mb-4">
                  <div className="text-xs font-semibold text-gray-500 mb-2">Conteúdo:</div>
                  <div className="flex flex-wrap gap-2">
                    {material.topics.slice(0, 2).map((topic, idx) => (
                      <span
                        key={idx}
                        className="text-xs bg-gray-100 text-gray-700 px-2 py-1 rounded"
                      >
                        {topic}
                      </span>
                    ))}
                  </div>
                </div>

                {/* Botão */}
                <button className="w-full btn-primary text-sm py-2 group-hover:scale-105">
                  Estudar Agora
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </DashboardLayout>
  );
};

export default EstudosPage;
